"""initial

Revision ID: c9fad880fde4
Revises: 
Create Date: 2024-02-06 21:59:42.392937

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'c9fad880fde4'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('clientes',
    sa.Column('cliente_id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('nombre', sa.String(), nullable=False),
    sa.Column('email', sa.String(), nullable=False),
    sa.Column('telefono', sa.String(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('cliente_id')
    )
    op.create_table('empresas',
    sa.Column('rnc', sa.String(), nullable=False),
    sa.Column('nombre', sa.String(), nullable=False),
    sa.Column('tipo_de_persona', sa.String(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('rnc')
    )
    op.create_table('organizaciones',
    sa.Column('organizacion_id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('nombre', sa.String(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('organizacion_id')
    )
    op.create_table('servicios',
    sa.Column('servicio_id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('nombre', sa.String(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('servicio_id')
    )
    op.create_table('tags',
    sa.Column('tag_id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('nombre', sa.String(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('tag_id')
    )
    op.create_table('usuarios',
    sa.Column('usuario_id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('nombre', sa.String(), nullable=False),
    sa.Column('email', sa.String(), nullable=False),
    sa.Column('password', sa.String(), nullable=False),
    sa.Column('status', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('rol', sa.String(), nullable=False),
    sa.PrimaryKeyConstraint('usuario_id')
    )
    op.create_index(op.f('ix_usuarios_email'), 'usuarios', ['email'], unique=False)
    op.create_table('clientes_empresas',
    sa.Column('cliente_id', sa.UUID(), nullable=False),
    sa.Column('rnc', sa.String(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['cliente_id'], ['clientes.cliente_id'], ),
    sa.ForeignKeyConstraint(['rnc'], ['empresas.rnc'], ),
    sa.PrimaryKeyConstraint('cliente_id', 'rnc')
    )
    op.create_table('cuentas',
    sa.Column('cuenta_id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('rnc', sa.String(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['rnc'], ['empresas.rnc'], ),
    sa.PrimaryKeyConstraint('cuenta_id')
    )
    op.create_index(op.f('ix_cuentas_rnc'), 'cuentas', ['rnc'], unique=True)
    op.create_table('organizaciones_usuarios',
    sa.Column('organizacion_id', sa.UUID(), nullable=False),
    sa.Column('usuario_id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['organizacion_id'], ['organizaciones.organizacion_id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['usuario_id'], ['usuarios.usuario_id'], ),
    sa.PrimaryKeyConstraint('organizacion_id', 'usuario_id')
    )
    op.create_table('tags_servicios',
    sa.Column('tag_id', sa.UUID(), nullable=False),
    sa.Column('servicio_id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['servicio_id'], ['servicios.servicio_id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['tag_id'], ['tags.tag_id'], ),
    sa.PrimaryKeyConstraint('tag_id', 'servicio_id')
    )
    op.create_table('cuentas_servicios',
    sa.Column('cuenta_id', sa.UUID(), nullable=False),
    sa.Column('servicio_id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['cuenta_id'], ['cuentas.cuenta_id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['servicio_id'], ['servicios.servicio_id'], ),
    sa.PrimaryKeyConstraint('cuenta_id', 'servicio_id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('cuentas_servicios')
    op.drop_table('tags_servicios')
    op.drop_table('organizaciones_usuarios')
    op.drop_index(op.f('ix_cuentas_rnc'), table_name='cuentas')
    op.drop_table('cuentas')
    op.drop_table('clientes_empresas')
    op.drop_index(op.f('ix_usuarios_email'), table_name='usuarios')
    op.drop_table('usuarios')
    op.drop_table('tags')
    op.drop_table('servicios')
    op.drop_table('organizaciones')
    op.drop_table('empresas')
    op.drop_table('clientes')
    # ### end Alembic commands ###
